title: "CogNetLab"
author: "Kirti Saluja"
description: "Loma Linda University Health, California"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", url: /}
  - {file: "research.md", title: "Research", url: /research/}
  - {file: "people.md", title: "People", url: /people/}
  - {file: "facilities.md", title: "Facility", url: /facilities/}
  - {file: "codes-data.md", title: "Codes & Data", url: /codes-data/}
  - {file: "contact.md", title: "Contact", url: /contact/}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
